version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  prebuild:
    working_directory: ~/circle
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: node prebuild.js
  build-and-test:
    working_directory: ~/circle
    docker:
      - image: circleci/python:3.6.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Test
          command: |
            pip install -r requirements.txt
            ./manage.py test

workflows:
  main:
    jobs:
      - prebuild
      - build-and-test:
          requires:
            - prebuild
