version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  database:
    docker:
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: mysite
          POSTGRES_DB: top-secret
    steps: []
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - database
      - build-and-test:
          requires:
            - database
