version: 2.1

jobs:
  build-and-test:
    working_directory: ~/circle
    docker:
      - image: lumakernel/cimg-python-node:3.6.9-12
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Test
          command: |
            node prebuild.js
            pip install -U pip
            pip install -r requirements.txt
            ./manage.py test

workflows:
  main:
    jobs:
      - build-and-test
